### ISSUE TITLE
status

### ISSUE THREAD

**Issue by tcharding** [stevenroose/rust-bitcoin-p2p#3]
Hey @stevenroose whats the status of this crate bro? I'm keen to pull the `network` module out of `rust-bitcoin`, rename it to `p2p` and make a crate of it - so `bitcoin-p2p`, I found this crate while looking into that. Would you be open to me merging the `network` crate with this one and moving it to the `rust-bitcoin` oragnisation, assuming that is technically feasable? I was hoping to create the `p2p` crate without doing too many changes to the current `network` module since the point of the crate smashing is to reduce the scope of current work in `rust-bitcoin` crate, so no API changes to current `network`  module. I only looked at this crate's contents briefly and I know basically zero about the bitcoin p2p layer.

Feel free to just off-the-cuff say no if this sounds like wasted effort, or a silly idea.

Cheers,
Tobin.

ref:
- https://github.com/rust-bitcoin/rust-bitcoin/issues/1855
- https://github.com/rust-bitcoin/rust-bitcoin/discussions/1859

**Comment by Kixunil** [comment]
If I understand the difference correctly, `bitcoin::network` only has types and deserialization functions, while this one also has logic. So naturally, if merging the crates is a problem we could call our `bitcoin-p2p-types`.

**Comment by stevenroose** [comment]
Actually been doing a total rewrite based on nakamoto's p2p module the last month. I'm targetting to have a working p2p crate ready here in a few months. Been a project of mine for a long time but only occasionally had time to work on this and kinda rewinded a few times on the design. But now I got something that I'm happy with and I'm just working it all out, step by step taking things from nakamoto's impl. Eventually the goal would be to (be able to) replace nakamoto's built-in p2p with this crate. (I'm talking with @cloudhead about this.)

But yeah the difference with rust-bitcoin's network module is that that module only has the data types and primitives while this crate aims to be a library that you can use to directly connect to the p2p network and interact with it. It's heavily using `bitcoin::network` for that and I have made several additions to `bitcoin::network` for the sake of this library.

**Comment by stevenroose** [comment]
I would definitely not want to have networking logic and the data types mixed in the same crate. I kinda think they're fine to be in rust-bitcoin as it is now. It's basically some message types and that's it. We could have `bitcoin-wire` for that or something (btcsuite calls their btcwire too). But for me it's fine as it is right now.

**Comment by tcharding** [comment]
Closing this as resolved, see https://github.com/rust-bitcoin/rust-bitcoin/discussions/1859#discussioncomment-6033883 for more.

**Comment by dr-orlovsky** [comment]
@stevenroose if you are interested in rewrite and Nakamoto, you may look at https://github.com/rust-amplify/io-reactor made by me and Nakamoto author @cloudhead for the next version of Nakamoto. It is an upgraded version of the same approach.

**Comment by stevenroose** [comment]
Hehe, I think I ended up building something quite similar to that. Basically a "green thread engine" where you can define processes that can hook into I/O events, timers and wakers. I'm not actually sure it's entirely the same, I don't really understand the API from io-reactor when looking at the docs. One thing, I haven't done for now is abstracting Poll using a trait, I just build on popol for now, but it's really a KISS impl for now. I'm planning to make bitcoin-p2p work with both this custom minimal engine or tokio optionally.
